### ISSUE TITLE
Raw data feed and full-flow testing

### ISSUE THREAD

**Issue by DeepAnonymous** [FernandoDeMeer/RL_Optimal_Execution#1]
Hello,

Thanks for sharing this repo. It's great to have such an open-source project.

However, I want to test data feed using HistoricalDataFeed instead of FakeLOBGenerator. Could you please provide data so that I can test and play around.

Also, instead of unit tests, how can run the project full-flow? where should I start __main__?

Thank you very much.

**Comment by FernandoDeMeer** [comment]
Hello, 

The data we used can be downloaded in this [link](https://drive.google.com/file/d/1m0hKK_TOr9VzKTlaTN8IKaLT2ozkLAWD/view?usp=sharing).

See the file `train_ppo.py` for an entrypoint to the experiment. Training an Agent via PPO can be done via the `main()` function. Equivalently, see `evaluate.py` in `src/core/eval` for code to evaluate a trained Agent.

**Comment by DeepAnonymous** [comment]
Thank you.

I have one more question regarding **TWAP**. How could I compare a trained agent with traditional TWAP algorithm?

Also, when investigating **test_execution_algo.py**, I cannot find how you calculate twap/vwap values and how to use it. For example, in this repo/file, https://github.com/NikhilSehgal123/coinbase-execution-algorithm/blob/d02ba459faf84444831fa82857a3599139e41caf/coinbase_algo.py#L179, I can see they compute **`self.vwap`** and check if **`PriceIsFavorable`** when deciding limit/market orders. But I cannot in your repo/algorithm.

**`self.vmap`** mentioned aboved could be calculated using https://blog.quantinsti.com/twap/ or https://blog.quantinsti.com/vwap-strategy/.

Could you please give some comments/insights about this. All in all, I want to benchmark your RL algorithm with TWAP.

Thank you.

**Comment by DeepAnonymous** [comment]
Here is part of my code when testing TWAP.

```
from src.core.environment.limit_orders_setup.execution_algo import TWAPAlgo, BUCKET_SIZES_IN_SECS
from src.core.environment.limit_orders_setup.broker import Broker
from src.data.historical_data_feed import HistoricalDataFeed

START_DATE_TIME ='2021-06-20 09:00:00'
END_DATE_TIME='2021-06-20 09:15:00'
ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '../..'))

class TestExecutionAlgo(unittest.TestCase):

    start_day = datetime(year=2021,month=6, day=20)
    end_day = datetime(year=2021,month=6, day=20)
    lob_feed = HistoricalDataFeed(data_dir=os.path.join(ROOT_DIR, 'data/market/btcusdt'),
                                  instrument='btcusdt', start_day=start_day, end_day=end_day)
    # fake_lob = FakeLOBGenerator()

    # define the benchmark algo
    algo = TWAPAlgo(trade_direction=1,
                    volume=25,
                    start_time=START_DATE_TIME,
                    end_time=END_DATE_TIME,
                    no_of_slices=1,
                    bucket_placement_func=lambda no_of_slices: 0.5,
                    broker_data_feed=lob_feed)

    # # define the broker class
    broker = Broker(lob_feed)
    broker.benchmark_algo = algo
    broker.simulate_algo(algo)
    
    def test_execution(self):
        # check the values of the first execution placed

        # self.assertEqual(datetime.strptime(self.broker.trade_logs['benchmark_algo'][0]['timestamp'],
        #                                    "%Y-%m-%d %H:%M:%S.%f").time().second,
        #                  4,
        #                  'First execution time does not seem correct')

        # find first trade...
        all_trades = [log for log in self.broker.trade_logs['benchmark_algo'] if log["message"] == "trade"]
        print(all_trades)
        self.algo.plot_schedule(all_trades)
        acc_quantity, acc_price = 0, 0
        for trade in all_trades:
            acc_quantity += trade['quantity']
            acc_price += trade['price'] * trade['quantity']
            print(trade['quantity'], trade['price'])
        print("acc: ", acc_quantity, acc_price/acc_quantity)
```

**Comment by FernandoDeMeer** [comment]
Hello, 

The function ``calc_vwap_from_logs()`` of the ``Broker`` ([link](https://github.com/FernandoDeMeer/RL_Optimal_Execution/blob/master/src/core/environment/limit_orders_setup/broker.py)) calculates the prices achieved by the TWAP benchmark and the RL Agent that we later on use to calculate the loss function we use to train (see its call in the ``step`` function of the ``BaseEnv`` [(link)](https://github.com/FernandoDeMeer/RL_Optimal_Execution/blob/master/src/core/environment/limit_orders_setup/broker.py)).

In your code, I would either take part of ``calc_vwap_from_logs()`` in order to take 1 algo at a time or rather declare also a RLAlgo as in the ``step`` function and then get the vwaps of both, up to you.
